#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 ThreadX Shell Project
#
# Emit a C++ byte array + size for a TFLite model, for the tflm NN backend
# (Epic #80 P3 M2, issue #88).  Used at CMake configure time by
# cmake/tflite-micro.cmake to turn the (gitignored, non-committed) BlazeFace
# .tflite into a compilable translation unit inside the `tflm` static lib.
#
# We roll our own generator (rather than tflite-micro's generate_cc_arrays.py)
# for two reasons: (1) a FIXED symbol name decoupled from the input filename, so
# nn_tflm.cc can #include a stable header regardless of which .tflite is fed;
# (2) no numpy/Pillow dependency.  The array is alignas(16) to satisfy TFLM's
# flatbuffer alignment requirement (tflite::GetModel expects a 16-byte-aligned
# buffer).
#
#   gen_model_array.py <input.tflite> <out.cc> <out.h> <symbol>
#
# Emits, for symbol `g_blazeface_model_data`:
#   out.h : extern const unsigned char  g_blazeface_model_data[];
#           extern const unsigned int   g_blazeface_model_data_size;
#   out.cc: alignas(16) const unsigned char g_blazeface_model_data[] = { ... };
#           const unsigned int g_blazeface_model_data_size = <N>;

import os
import sys


def main():
    if len(sys.argv) != 5:
        sys.stderr.write(
            "usage: gen_model_array.py <input.tflite> <out.cc> <out.h> <symbol>\n")
        return 1
    in_path, cc_path, h_path, symbol = sys.argv[1:5]

    with open(in_path, "rb") as f:
        blob = f.read()
    if not blob:
        sys.stderr.write("gen_model_array: empty model file: %s\n" % in_path)
        return 1

    os.makedirs(os.path.dirname(cc_path) or ".", exist_ok=True)
    os.makedirs(os.path.dirname(h_path) or ".", exist_ok=True)
    hdr_name = os.path.basename(h_path)

    with open(h_path, "w") as h:
        h.write("/* Auto-generated by cmake/gen_model_array.py -- do not edit. */\n")
        h.write("#ifndef TFLM_MODEL_ARRAY_%s_H\n" % symbol.upper())
        h.write("#define TFLM_MODEL_ARRAY_%s_H\n\n" % symbol.upper())
        h.write("extern const unsigned char %s[];\n" % symbol)
        h.write("extern const unsigned int  %s_size;\n\n" % symbol)
        h.write("#endif\n")

    with open(cc_path, "w") as cc:
        cc.write("/* Auto-generated by cmake/gen_model_array.py -- do not edit. */\n")
        cc.write('#include "%s"\n\n' % hdr_name)
        cc.write("alignas(16) const unsigned char %s[] = {\n" % symbol)
        # 16 bytes per line keeps the file readable and diffs sane.
        for i in range(0, len(blob), 16):
            row = blob[i:i + 16]
            cc.write("  " + ",".join("0x%02x" % b for b in row) + ",\n")
        cc.write("};\n")
        cc.write("const unsigned int %s_size = %du;\n" % (symbol, len(blob)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
